### ISSUE TITLE
How to deal with multiple tokens for one word?

### ISSUE THREAD

**Issue by liujuncn** [mega002/lm-debugger#7]
How to analyze words that need to be represented by multiple subword tokens in vocabulary?

For example sentence: "爱是一种特殊的情感" ("love is a special emotion" in English).
Because of the vocabulary of GPT2, a Chinese character is divided into multiple tokens by BBPE. So it seems that the complete semantics cannot be obtained by Search by Keyword and Trace functions.

![image](https://github.com/mega002/lm-debugger/assets/902005/f565aa35-6c5b-4f64-9ae4-8054b95ffaf2)

Although the vocabularies of the GPT series lack entries for CJK character set words, they still have good text generation performance. Therefore, how to effectively study the representation of continuous subwords in the embedding space?  Can the activation outputs of tokens that make up complete words be summed?

**Comment by mega002** [comment]
Thanks for your question.

Inspection through projection to the vocabulary is inherently limited to the set of tokens available in the vocabulary. Due to this limitation, this method (when applied as-is) might not be great for some cases, like the one mentioned in that thread.

Perhaps this can be mitigated by obtaining word representations from existing vocabulary items, but this needs to be investigated -- as far as I know, there's no out-of-the-box solution for this at the moment.
